current_dir = $(shell cd)

ifndef day
$(error day is not set)
endif

# make -f makefile.win day=01 run
run:
	bazel run //day$(day):main $(current_dir)/day$(day)/input.txt

# make -f makefile.win day=14 example
example:
	bazel run //day$(day):main $(current_dir)/day$(day)/example.txt

# make -f makefile.win day=00 test
test:
	bazel run //day$(day):main

# make -f makefile.win day=05 generate
generate:
	cp -r template day$(day)

install:
	brew install bazel